include(":firebase-google")
include(
        ":app",
        "core",
        "firebase-core",
        ":firebase-facebook",
        ":google-core",
        ":facebook-core",
        ":google",
        ":facebook"
)
