include(
        ":app",
        ":core",
        ":google-core",
        ":facebook-core",
        ":rx-google",
        ":rx-facebook",
        ":rx-firebase",
        ":rx-firebase-facebook",
        ":rx-firebase-google",
        ":arrow-google",
        ":arrow-facebook"
)
