import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    /**
     * [appcompat website](http://developer.android.com/tools/extras/support-library.html) */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * [constraintlayout website](http://tools.android.com) */
    const val constraintlayout: String =
            "androidx.constraintlayout:constraintlayout:" + Versions.constraintlayout

    /**
     * [core-ktx website](http://developer.android.com/tools/extras/support-library.html) */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * [espresso-core website](https://developer.android.com/testing) */
    const val espresso_core: String =
            "androidx.test.espresso:espresso-core:" + Versions.espresso_core

    /**
     * [runner website](https://developer.android.com/testing) */
    const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test_runner

    /**
     * [aapt2 website](https://developer.android.com/studio) */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val com_android_tools_build_gradle: String =
            "com.android.tools.build:gradle:" + Versions.com_android_tools_build_gradle

    /**
     * [lint-gradle website](https://developer.android.com/studio) */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * [facebook-core website](https://github.com/facebook/facebook-android-sdk) */
    const val facebook_core: String =
            "com.facebook.android:facebook-core:" + Versions.com_facebook_android

    /**
     * [facebook-login website](https://github.com/facebook/facebook-android-sdk) */
    const val facebook_login: String =
            "com.facebook.android:facebook-login:" + Versions.com_facebook_android

    /**
     * [inline-activity-result-kotlin website](https://github.com/florent37/InlineActivityResult) */
    const val inline_activity_result_kotlin: String =
            "com.github.florent37:inline-activity-result-kotlin:" + Versions.inline_activity_result_kotlin

    const val kotlin_functional_extensions_android: String =
            "com.github.giacomoParisi.kotlin-functional-extensions:kotlin-functional-extensions-android:" + Versions.com_github_giacomoparisi_kotlin_functional_extensions

    const val kotlin_functional_extensions_arrow: String =
            "com.github.giacomoParisi.kotlin-functional-extensions:kotlin-functional-extensions-arrow:" + Versions.com_github_giacomoparisi_kotlin_functional_extensions

    const val kotlin_functional_extensions_core: String =
            "com.github.giacomoParisi.kotlin-functional-extensions:kotlin-functional-extensions-core:" + Versions.com_github_giacomoparisi_kotlin_functional_extensions

    const val play_services_auth: String =
            "com.google.android.gms:play-services-auth:" + Versions.play_services_auth

    const val firebase_auth: String = "com.google.firebase:firebase-auth:" + Versions.firebase_auth

    /**
     * [google-services website](http://tools.android.com/) */
    const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

    const val arrow_annotations_processor: String =
            "io.arrow-kt:arrow-annotations-processor:" + Versions.io_arrow_kt

    const val arrow_core: String = "io.arrow-kt:arrow-core:" + Versions.io_arrow_kt

    const val arrow_data: String = "io.arrow-kt:arrow-data:" + Versions.io_arrow_kt

    const val arrow_effects_kotlinx_coroutines: String =
            "io.arrow-kt:arrow-effects-kotlinx-coroutines:" + Versions.io_arrow_kt

    const val arrow_effects: String = "io.arrow-kt:arrow-effects:" + Versions.io_arrow_kt

    const val arrow_instances_core: String =
            "io.arrow-kt:arrow-instances-core:" + Versions.io_arrow_kt

    const val arrow_instances_data: String =
            "io.arrow-kt:arrow-instances-data:" + Versions.io_arrow_kt

    const val arrow_syntax: String = "io.arrow-kt:arrow-syntax:" + Versions.io_arrow_kt

    /**
     * [arrow-typeclasses website](https://github.com/arrow-kt/arrow/) */
    const val arrow_typeclasses: String = "io.arrow-kt:arrow-typeclasses:" + Versions.io_arrow_kt

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * [kotlin-android-extensions-runtime website](https://kotlinlang.org/) */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-android-extensions website](https://kotlinlang.org/) */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-annotation-processing-gradle website](https://kotlinlang.org/) */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-stdlib-jdk7 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk7: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlinx-coroutines-android website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" + Versions.kotlinx_coroutines_android
}
