import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val com_github_bumptech_glide: String = "4.11.0"

    const val com_facebook_android: String = "7.1.0"

    const val org_jetbrains_kotlin: String = "1.4.0"

    const val org_jetbrains_dokka: String = "0.9.18"

    const val io_arrow_kt: String = "0.10.5"

    const val com_android_tools_build_gradle: String = "4.0.1"

    const val androidx_test_runner: String = "1.2.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val inline_activity_result_kotlin: String = "1.0.4"

    const val android_maven_gradle_plugin: String = "2.1"

    const val gradle_bintray_plugin: String = "1.8.5"

    const val play_services_auth: String = "18.1.0"

    const val constraintlayout: String = "2.0.0"

    const val google_services: String = "4.3.3"

    const val espresso_core: String = "3.2.0"

    const val firebase_auth: String = "19.3.2"

    const val lint_gradle: String = "27.0.1"

    const val appcompat: String = "1.2.0"

    const val rxandroid: String = "2.1.1"

    const val core_ktx: String = "1.3.1"

    const val rxkotlin: String = "2.4.0"

    const val rxjava: String = "2.2.19"

    const val aapt2: String = "4.0.1-6197926"

    const val junit: String = "4.13"

    /**
     * Current version: "6.2.2"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.6"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
