import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.4.2" // available: "1.4.2"

    const val com_github_bumptech_glide: String = "4.11.0"

    const val com_facebook_android: String = "8.1.0"

    const val org_jetbrains_kotlin: String = "1.4.20" // available: "1.4.20"

    const val org_jetbrains_dokka: String = "0.9.18"

    const val io_arrow_kt: String = "0.11.0"

    const val com_android_tools_build_gradle: String = "4.1.1" // available: "4.1.1"

    const val androidx_test_runner: String = "1.3.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val inline_activity_result_kotlin: String = "1.0.4"

    const val android_maven_gradle_plugin: String = "2.1"

    const val gradle_bintray_plugin: String = "1.8.5"

    const val play_services_auth: String = "19.0.0" // available: "19.0.0"

    const val constraintlayout: String = "2.0.4"

    const val google_services: String = "4.3.4"

    const val espresso_core: String = "3.3.0"

    const val firebase_auth: String = "20.0.1" // available: "20.0.1"

    const val lint_gradle: String = "27.1.1" // available: "27.1.1"

    const val appcompat: String = "1.2.0"

    const val core_ktx: String = "1.3.2"

    const val aapt2: String = "4.1.1-6503028" // available: "4.1.1-6503028"

    const val junit: String = "4.13.1"

    /**
     * Current version: "6.7"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.7.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
